config/routes.rb
Lists::Application.routes.draw do
  resources :lists

end

app/models/list.rb
class List < ActiveRecord::Base
  
  has_many :list_items, :dependent => :destroy
  accepts_nested_attributes_for :list_items, :reject_if => lambda { |a| a[:item].blank? }, :allow_destroy => true
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    
  end

  def new
    @list = List.new
    4.times { @list.list_items.build }
  end

  def create
    @list = List.new(params[:list])
    if @list.save
      redirect_to @list, :notice => "Successfully created list."
    else
      render :action => 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      redirect_to @list, :notice  => "Successfully updated list."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_url, :notice => "Successfully destroyed list."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js", "rails.js", "application.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<p>
  	<%= f.label :name, "List Name" %></br>
	<%= f.text_field :name %>
</p>

<%= f.fields_for :list_items do |builder| %>  
  <p class='item'>  
    <%= builder.label :item %><br />  
    <%= builder.text_field :item, :size => 40 %>  
  </p>  
  <% end %>

<a href='/' id='add'>Add Item</a>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= form_for @list do |f| %>
  <% if @list.errors.any? %>  
  <div class='error'>  
    <h2><%= pluralize(@list.errors.count, "error") %> prevent this list from being saved:</h2>  
    <ul>  
    <% @list.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>
 <% end %>
	
	<%= render :partial => 'form', :locals => {:f => f} %>

	 <%= f.submit "Update List" %>
<% end %>

app/views/lists/index.html.erb
<% title "Lists" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for list in @lists %>
    <tr>
      <td><%= list.name %></td>
      <td><%= link_to "Show", list %></td>
      <td><%= link_to "Edit", edit_list_path(list) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New List", new_list_path %></p>

app/views/lists/new.html.erb
<h1>Create New List</h1>

<%= form_for @list do |f| %>
  <% if @list.errors.any? %>  
  <div class='error'>  
    <h2><%= pluralize(@list.errors.count, "error") %> prevent this list from being saved:</h2>  
    <ul>  
    <% @list.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>
 <% end %>
	
	<%= render :partial => 'form', :locals => {:f => f} %>
	
	<%= f.submit "Create List" %>
<% end %>

app/views/lists/show.html.erb
<% title "List" %>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>
<ol>
	<% @list.list_items.each do |li| %>
	<li><%= li.item %></li>
	<% end %>
</ol>

<p>
  <%= link_to "Edit", edit_list_path(@list) %> |
  <%= link_to "View All", lists_path %>
</p>